<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<LangVersion>latest</LangVersion>
		<PlatformTarget>x64</PlatformTarget>
		<TargetFramework>net48</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="bundle\**" />
	  <EmbeddedResource Remove="bundle\**" />
	  <None Remove="bundle\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\RincovitchIcon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Resources\RincovitchIcon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="WixSharp.bin" Version="1.26.0" />
		<PackageReference Include="WixSharp.wix.bin" Version="3.14.1" />
	</ItemGroup>

</Project>
